### ISSUE TITLE
Can't Access ColorPickerWheel Control from Code Behind

### ISSUE THREAD

**Issue by tpitman** [newky2k/DSoft.XamarinForms.Controls#10]
I am trying to use the ColorPickerWheel that you wrapped. I love it! Thank you.

I am having one problem. When I put something like x:Name="LabelColorPicker" in the xaml for the ColorWheelView, I can't access it in the code behind file.

I am able to have the ColorChanged="ColorWheelView_ColorChanged" in my code behind and it fires just fine.

Even better I wish I could bind the current color to a View Model using normal binding, but there doesn't seem to be any property in the ColorWheelView that I can bind to.

I want to access the ColorWheelView control in my code behind so I can set the color at will. Currently I don't see a way to do that.

**Comment by newky2k** [comment]
@tpitman Thanks for getting in touch.

I'm not sure why using x:Name would not show up in the code behind, thats a function of Xaml and Xamarin.Forms rather than the control itself, i can take a look though. What version of Xamarin.Forms are you using?

I did look at creating a bindable property for "SelectedColor" but it was an issue about locating the correct point to move the "selector" too when setting it externally.  I never got back round to doing it.

**Comment by tpitman** [comment]
I came upon the same issue with trying to find the right color in the color wheel. I decided to go a different direction that doesn't require that.

Thank you for your reply.
